In [5]:
#Preprocessing images
##Figuring out how to turn images into just black and white

import cv2 
import numpy as np 

In [22]:
#Edge Detector
FILE_NAME = 'sample_cracks_eda/Screen Shot 2020-01-09 at 1.58.48 PM.png'
try: 
    # Read image from disk. 
    img = cv2.imread(FILE_NAME) 
  
    # Canny edge detection. 
    edges = cv2.Canny(img, 150, 200) 
  
    # Write image back to disk. 
    cv2.imwrite('result.jpg', edges)
except IOError: 
    print ('Error while reading files !!!') 

In [65]:
#Grayscaling
image = cv2.imread('sample_cracks_eda/Screen Shot 2020-01-09 at 1.58.48 PM.png', 0)
cv2.imwrite('result.jpg', image)

True

In [66]:
image

array([[80, 50, 38, ..., 42, 50, 51],
       [63, 43, 46, ..., 58, 54, 46],
       [46, 31, 43, ..., 50, 47, 43],
       ...,
       [42, 20, 26, ..., 34, 33, 41],
       [32, 29, 40, ..., 29, 40, 47],
       [31, 33, 50, ..., 31, 39, 45]], dtype=uint8)

In [34]:
image2 = cv2.imread('sample_cracks_eda/Screen Shot 2020-01-09 at 1.02.27 PM.png', 0)
cv2.imwrite('result2.jpg', image2)

True

In [35]:
image3 = cv2.imread('sample_cracks_eda/Screen Shot 2020-01-09 at 11.53.05 AM.png', 0)
cv2.imwrite('result3.jpg', image3)

True

In [37]:
image4 = cv2.imread('sample_cracks_eda/Screen Shot 2020-01-09 at 12.59.40 PM.png', 0)
cv2.imwrite('result4.jpg', image4)

True

In [6]:
import os

In [7]:
#Figuring out how to loop through a folder of images to grayscale at once
import cv2
from os import listdir,makedirs
from os.path import isfile,join

path = r'sample_cracks_eda' # Source Folder
dstpath = r'sample_grayscale_eda' # Destination Folder

try:
    makedirs(dstpath)
except:
    print ("Directory already exist, images will be written in asme folder")

# Folder won't used
files = [f for f in listdir(path) if isfile(join(path,f))] 

for image in files:
    try:
        img = cv2.imread(os.path.join(path,image), 0)
        dstPath = join(dstpath,image)
        cv2.imwrite(dstPath,img)
    except:
        print("{} is not converted".format(image))

Directory already exist, images will be written in asme folder
.DS_Store is not converted


In [8]:
#Figuring out how to access the images in AWS s3 bucket
import logging
import boto3
from botocore.exceptions import ClientError

In [46]:
s3 = boto3.client('s3')

In [45]:
! aws s3 ls

2020-01-04 23:06:45 art.forgery.capstone.project
2020-01-02 11:21:44 fis-seoho-demo


In [78]:
response = s3.get_object(Bucket='art.forgery.capstone.project', Key='data/train/Dutch/Dutch1,000.png')

In [89]:
response['Body'].read()

b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01\x00\x00\x00\x01\x00\x08\x06\x00\x00\x00\\r\xa8f\x00\x00\x01@iCCPICC Profile\x00\x00(\x91c``\xe2I,(\xc8aa``\xc8\xcd+)\nrwR\x88\x88\x8cR`\x7f\xc2\xc0\xc8\xc0\xc9\xc0\xc5 \xc5 \x9f\x98\\\\\xe0\x18\x10\xe0\x03T\xc2\x00\xa3Q\xc1\xb7k@\xd5@pY\x17d\xd6\x8c\x0f\xff\x0e\xd9\xf1M\x89\x0e\xb4\x8d:7\xbb\xaeU\x10S=\n\xe0JI-N\x06\xd2\x7f\x808!\xb9\xa0\xa8\x84\x81\x811\x06\xc8V./)\x00\xb1\x1b\x80l\x91"\xa0\xa3\x80\xec) v:\x84\xbd\x02\xc4N\x82\xb0\xf7\x80\xd5\x84\x049\x03\xd9\x17\x80l\x81\xe4\x8c\xc4\x14 \xfb\x01\x90\xad\x93\x84$\x9e\x8e\xc4\x86\xda\x0b\x02la\xc1F&\x16\x04\x1cJ*(I\xad(\x01\xd1\xce\xf9\x05\x95E\x99\xe9\x19%\n\x8e\xc0\xd0IU\xf0\xccK\xd6\xd3Q0202``\x00\x855D\xf5\xe7\x1b\xe00d\x14\xe3@\x88\xc5^b`\xd0\x9f\x08\xf27B,_\x9c\x81\xe1\x10\x07\x03\x03O1BL\xf3\r\x03\x03_\x1a\x03\xc3Q\xb5\x82\xc4\xa2D\xb8\x03\x18\xbf\xb1\x14\xa7\x19\x1bA\xd8\xdc\xdb\x19\x18X\xa7\xfd\xff\xff9\x9c\x81\x81]\x93\x81\xe1\xef\xf5\xff\xff\x7fo\xff\xff\xff\xef2\x06\x06\xe6[

In [1]:
bucket = 'art.forgery.capstone.project'
key = 'data/train/Dutch/Dutch1,001.png'

In [9]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import boto3
import tempfile

s3 = boto3.resource('s3')

bucket = s3.Bucket('art.forgery.capstone.project')

object = bucket.Object('data/train/Dutch/Dutch1,001.png')

tmp = tempfile.NamedTemporaryFile()

with open(tmp.name, 'wb') as f:

    object.download_fileobj(f)

    img=cv2.imread(tmp.name, 0)

In [103]:
cv2.imwrite('result5.jpg', img)

True

In [104]:
img

array([[18, 20, 21, ..., 18, 19, 19],
       [18, 17, 18, ..., 17, 18, 19],
       [22, 18, 18, ..., 17, 19, 19],
       ...,
       [18, 21, 20, ..., 19, 18, 19],
       [19, 21, 19, ..., 18, 18, 20],
       [20, 17, 17, ..., 18, 18, 20]], dtype=uint8)

In [31]:
s3 = boto3.resource('s3')
bucket = s3.Bucket('art.forgery.capstone.project')
tmp = tempfile.NamedTemporaryFile()

def greyscaling(obj):
    with open(tmp.name, 'wb') as f:
        obj.download_fileobj(f)
    return cv2.imread(tmp.name, 0)
dutch_train_imgs = []            
for object in bucket.objects.filter(Prefix='data/train/Dutch/'):
    obj = bucket.Object(str(object.key))
    dutch_train_imgs.append(greyscaling(obj))

In [33]:
dutch_train_imgs = dutch_train_imgs[1:-1]

In [35]:
dutch_train_imgs[:2]

[array([[32, 21, 18, ..., 20, 20, 20],
        [28, 23, 23, ..., 19, 19, 22],
        [23, 23, 25, ..., 18, 18, 21],
        ...,
        [17, 17, 17, ..., 24, 23, 17],
        [17, 17, 16, ..., 22, 20, 20],
        [17, 17, 15, ..., 20, 17, 19]], dtype=uint8),
 array([[18, 20, 21, ..., 18, 19, 19],
        [18, 17, 18, ..., 17, 18, 19],
        [22, 18, 18, ..., 17, 19, 19],
        ...,
        [18, 21, 20, ..., 19, 18, 19],
        [19, 21, 19, ..., 18, 18, 20],
        [20, 17, 17, ..., 18, 18, 20]], dtype=uint8)]

In [26]:
import time
import matplotlib.pyplot as plt
import scipy
import numpy as np
from PIL import Image
from scipy import ndimage
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

np.random.seed(123)

Using TensorFlow backend.


In [36]:
datagen = ImageDataGenerator(preprocessing_function=greyscaling(obj))

In [40]:
import os

A = os.path.join(os.path.dirname(__file__), '..')
# A is the parent directory of the directory where program resides.

B = os.path.dirname(os.path.realpath(__file__))
# B is the canonicalised (?) directory where the program resides.

C = os.path.abspath(os.path.dirname(__file__))

print(__file__)
print(os.path.join(os.path.dirname(__file__), '..'))
print(os.path.dirname(os.path.realpath(__file__)))
print(os.path.abspath(os.path.dirname(__file__)))

NameError: name '__file__' is not defined