In [3]:
#Preprocessing images
##Figuring out how to turn images into grayscale

import cv2 
import numpy as np 

In [22]:
#Edge Detector
FILE_NAME = '../sample_cracks_eda/Screen Shot 2020-01-09 at 1.58.48 PM.png'
try: 
    # Read image from disk. 
    img = cv2.imread(FILE_NAME) 
  
    # Canny edge detection. 
    edges = cv2.Canny(img, 150, 200) 
  
    # Write image back to disk. 
    cv2.imwrite('result.jpg', edges)
except IOError: 
    print ('Error while reading files !!!') 

In [65]:
#Grayscaling
image = cv2.imread('../sample_cracks_eda/Screen Shot 2020-01-09 at 1.58.48 PM.png', 0)
cv2.imwrite('result.jpg', image)

True

In [66]:
image

array([[80, 50, 38, ..., 42, 50, 51],
       [63, 43, 46, ..., 58, 54, 46],
       [46, 31, 43, ..., 50, 47, 43],
       ...,
       [42, 20, 26, ..., 34, 33, 41],
       [32, 29, 40, ..., 29, 40, 47],
       [31, 33, 50, ..., 31, 39, 45]], dtype=uint8)

In [34]:
image2 = cv2.imread('../sample_cracks_eda/Screen Shot 2020-01-09 at 1.02.27 PM.png', 0)
cv2.imwrite('result2.jpg', image2)

True

In [4]:
image3 = cv2.imread('../data/Cracks/train/Dutch/Dutch3.png', 0)
cv2.imwrite('Dutch3_grayscale.jpg', image3)

True

In [37]:
image4 = cv2.imread('../sample_cracks_eda/Screen Shot 2020-01-09 at 12.59.40 PM.png', 0)
cv2.imwrite('result4.jpg', image4)

True

In [6]:
import os

In [8]:
#Figuring out how to loop through a folder of images to grayscale at once
import cv2
from os import listdir,makedirs
from os.path import isfile,join

path = r'../sample_cracks_eda' # Source Folder
dstpath = r'../sample_grayscale_eda' # Destination Folder

try:
    makedirs(dstpath)
except:
    print ("Directory already exist, images will be written in asme folder")

# Folder won't used
files = [f for f in listdir(path) if isfile(join(path,f))] 

for image in files:
    try:
        img = cv2.imread(os.path.join(path,image), 0)
        dstPath = join(dstpath,image)
        cv2.imwrite(dstPath,img)
    except:
        print("{} is not converted".format(image))

Directory already exist, images will be written in asme folder
Screen Shot 2020-01-09 at 1.58.48 PM.png is not converted
.DS_Store is not converted
Screen Shot 2020-01-09 at 11.52.51 AM.png is not converted
Screen Shot 2020-01-09 at 11.54.30 AM.png is not converted
Screen Shot 2020-01-09 at 11.51.23 AM.png is not converted
Screen Shot 2020-01-09 at 1.58.52 PM.png is not converted
Screen Shot 2020-01-09 at 2.01.35 PM.png is not converted
Screen Shot 2020-01-09 at 1.02.27 PM.png is not converted
Screen Shot 2020-01-09 at 1.16.35 PM.png is not converted
Screen Shot 2020-01-09 at 12.06.33 PM.png is not converted
Screen Shot 2020-01-09 at 12.06.47 PM.png is not converted
Screen Shot 2020-01-09 at 11.53.46 AM.png is not converted
Screen Shot 2020-01-09 at 2.01.04 PM.png is not converted
Screen Shot 2020-01-09 at 11.50.16 AM.png is not converted
Screen Shot 2020-01-09 at 11.53.27 AM.png is not converted
Screen Shot 2020-01-09 at 12.59.37 PM.png is not converted
Screen Shot 2020-01-09 at 11.46

In [9]:
#Figuring out how to access the images in AWS s3 bucket
import logging
import boto3
from botocore.exceptions import ClientError

In [46]:
s3 = boto3.client('s3')

In [45]:
! aws s3 ls

2020-01-04 23:06:45 art.forgery.capstone.project
2020-01-02 11:21:44 fis-seoho-demo


In [78]:
response = s3.get_object(Bucket='art.forgery.capstone.project', Key='data/train/Dutch/Dutch1,000.png')

In [1]:
# response['Body'].read()

In [1]:
bucket = 'art.forgery.capstone.project'
key = 'data/train/Dutch/Dutch1,001.png'

In [7]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import boto3
import tempfile

s3 = boto3.resource('s3')

bucket = s3.Bucket('art.forgery.capstone.project')

object = bucket.Object('data/train/Dutch/Dutch1,001.png')

tmp = tempfile.NamedTemporaryFile()

with open(tmp.name, 'wb') as f:

    object.download_fileobj(f)

    img=cv2.imread(tmp.name, 0)

NameError: name 'cv2' is not defined

In [103]:
cv2.imwrite('result5.jpg', img)

True

In [104]:
img

array([[18, 20, 21, ..., 18, 19, 19],
       [18, 17, 18, ..., 17, 18, 19],
       [22, 18, 18, ..., 17, 19, 19],
       ...,
       [18, 21, 20, ..., 19, 18, 19],
       [19, 21, 19, ..., 18, 18, 20],
       [20, 17, 17, ..., 18, 18, 20]], dtype=uint8)

In [10]:
s3 = boto3.resource('s3')
bucket = s3.Bucket('art.forgery.capstone.project')
tmp = tempfile.NamedTemporaryFile()

def greyscaling(obj):
    with open(tmp.name, 'wb') as f:
        obj.download_fileobj(f)
    return cv2.imread(tmp.name, 0)

In [31]:
dutch_train_imgs = []            
for object in bucket.objects.filter(Prefix='data/train/Dutch/'):
    obj = bucket.Object(str(object.key))
    dutch_train_imgs.append(greyscaling(obj))

In [33]:
dutch_train_imgs = dutch_train_imgs[1:-1]

In [35]:
dutch_train_imgs[:2]

[array([[32, 21, 18, ..., 20, 20, 20],
        [28, 23, 23, ..., 19, 19, 22],
        [23, 23, 25, ..., 18, 18, 21],
        ...,
        [17, 17, 17, ..., 24, 23, 17],
        [17, 17, 16, ..., 22, 20, 20],
        [17, 17, 15, ..., 20, 17, 19]], dtype=uint8),
 array([[18, 20, 21, ..., 18, 19, 19],
        [18, 17, 18, ..., 17, 18, 19],
        [22, 18, 18, ..., 17, 19, 19],
        ...,
        [18, 21, 20, ..., 19, 18, 19],
        [19, 21, 19, ..., 18, 18, 20],
        [20, 17, 17, ..., 18, 18, 20]], dtype=uint8)]

In [4]:
import time
import matplotlib.pyplot as plt
import scipy
import numpy as np
from PIL import Image
from scipy import ndimage
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

np.random.seed(123)

Using TensorFlow backend.


In [14]:
import boto3
import os
import zipfile
from PIL import Image
from botocore.exceptions import ClientError

bucket_name = 'art.forgery.capstone.project'

s3 = boto3.client('s3')
try:
    print("Checking bucket ...")
    s3.head_bucket(Bucket=bucket_name)
except ClientError as e:
    print("Bucket not existing, creating it ...")
    s3.create_bucket(Bucket=bucket_name, ACL="private", CreateBucketConfiguration={'LocationConstraint': 'EU'})

zip_dataset = "Cracks2.zip"
tmp_dest = os.path.join(os.path.dirname(__file__), "tmp")
data_dir = os.path.join(os.path.dirname(__file__), "cracks")

if not os.path.exists(tmp_dest):
    os.mkdir(tmp_dest)

if len(os.listdir(tmp_dest)) <= 0:
    print("Unzipping archive ...")
    with zipfile.ZipFile(zip_dataset, 'r') as zip_ref:
        zip_ref.extractall(tmp_dest)

dutch_dir = tmp_dest + "/Dutch"
flemish_dir = tmp_dest + "/Flemish"

train_dir = data_dir + "/train/"
validation_dir = data_dir + "/validation/"

print("Checking directories ...")
for dir in [data_dir, train_dir, validation_dir]:
    if not os.path.exists(dir):
        os.mkdir(dir)

Checking bucket ...


NameError: name '__file__' is not defined

In [65]:
from PIL import Image 
image_file = Image.open("../data/Cracks/train/Dutch/Dutch1,077.png") # open colour image
image_file = image_file.convert('1') # convert image to black and white
image_file.save('resultbw.png')

np.array(image_file).shape

(256, 256)

In [88]:
def binarize_image(img_path, threshold):
    """Binarize an image."""
    image_file = Image.open(img_path)
    image = image_file.convert('L')  # convert image to monochrome
    image = np.array(image)
    for i in range(len(image)):
        for j in range(len(image[0])):
            if image[i][j] > threshold:
                image[i][j] = 255
            else:
                image[i][j] = 0
    return image

In [114]:
data = binarize_image(img_path="../data/Cracks/train/Dutch/Dutch1,022.png", threshold=70)

In [118]:
bwimage = Image.fromarray(data)

In [119]:
bwimage.save('../data/bwcracks/train/Dutch/Dutch1.png')